{
 "title": "Carburant_SAE_204_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Évolution d'achat des carburants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT DATE(p.date_prix_maj) AS date_jour , c.nom_carburant ,\nROUND(AVG(p.prix_carburant), 3) AS prix_moyen,\nCOUNT(DISTINCT p.id_station) AS total_stations_vendent \nFROM prix p \nJOIN carburant c ON p.id_carburant = c.id_carburant\nGROUP BY DATE(p.date_prix_maj), c.nom_carburant\nORDER BY date_jour ASC ; "
    }
   ]
  },
  {
   "title": "top 10 - sp95 le moins cher ( hors autoroute )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT s.id_station, s.nom_ville, p.prix_carburant \nFROM station s \nJOIN prix p ON s.id_station = p.id_station \nJOIN carburant c ON p.id_carburant = c.id_carburant \nWHERE c.nom_carburant = 'SP95' \nAND s.pop = 'R' \nORDER BY p.prix_carburant ASC \nLIMIT  10 ; "
    }
   ]
  },
  {
   "title": "top 10 - Gazole le moins cher ( hors autoroute )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT s.id_station, s.nom_ville, p.prix_carburant \nFROM station s \nJOIN prix p ON s.id_station = p.id_station \nJOIN carburant c ON p.id_carburant = c.id_carburant \nWHERE c.nom_carburant = 'Gazole' \nAND s.pop = 'R' \nORDER BY p.prix_carburant \nASC LIMIT  10; "
    }
   ]
  },
  {
   "title": "top 10 - SP98 le moins cher ( hors autoroute )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT  s.id_station, s.nom_ville, p.prix_carburant \nFROM station s \nJOIN prix p ON s.id_station = p.id_station \nJOIN carburant c ON p.id_carburant = c.id_carburant \nWHERE c.nom_carburant = 'SP98' \nAND s.pop = 'R' \nORDER BY p.prix_carburant \nASC LIMIT  10; "
    }
   ]
  },
  {
   "title": "Prix carburant en fonction du département (SP95)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n   s.code_departement,\n   AVG(p.prix_carburant) AS prix_moyen\nFROM station s\nJOIN prix p ON p.id_station = s.id_station\nJOIN carburant c ON p.id_carburant = c.id_carburant\nWHERE c.nom_carburant = 'SP95'\nAND s.code_departement <> '99'\nGROUP BY s.code_departement\nORDER BY prix_moyen DESC;"
    }
   ]
  },
  {
   "title": "Prix du carburant en fonction du département (Gazole)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    s.code_departement, \n    AVG(p.prix_carburant) AS prix_moyen\nFROM station s\nJOIN prix p ON p.id_station = s.id_station\nJOIN carburant c ON p.id_carburant = c.id_carburant\nWHERE c.nom_carburant = 'Gazole'\nAND s.code_departement <> '99'\nGROUP BY s.code_departement\nORDER BY prix_moyen DESC;\n"
    }
   ]
  },
  {
   "title": "Répartion des ruptures par type de carburant (définitive)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT c.nom_carburant, r.type_rupture ,COUNT(r.id_station) AS nombre_rupture \nFROM rupture r \nJOIN carburant c ON r.id_carburant = c.id_carburant\nWHERE  r.type_rupture='definitive'\nGROUP BY c.nom_carburant,r.type_rupture\nORDER BY nombre_rupture DESC; \n"
    }
   ]
  },
  {
   "title": "Répartition des rupture par type de carburant  (temporaire)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT c.nom_carburant, r.type_rupture ,COUNT(r.id_station) AS nombre_rupture \nFROM rupture r \nJOIN carburant c ON r.id_carburant = c.id_carburant\nWHERE  r.type_rupture='temporaire'\nGROUP BY c.nom_carburant,r.type_rupture\nORDER BY nombre_rupture DESC; \n"
    }
   ]
  },
  {
   "title": "Visualisation global de la france pour chaque station",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT \n    s.id_station,\n    s.nom_ville,\n    s.latitude,\n    s.longitude,\n    MAX(CASE WHEN c.nom_carburant = 'Gazole' THEN p.prix_carburant END) AS prix_gazole,\n    MAX(CASE WHEN c.nom_carburant = 'SP95' THEN p.prix_carburant END) AS prix_sp95,\n    MAX(CASE WHEN c.nom_carburant = 'SP98' THEN p.prix_carburant END) AS prix_sp98,\n    MAX(CASE WHEN c.nom_carburant = 'E10' THEN p.prix_carburant END) AS prix_e10,\n    MAX(CASE WHEN c.nom_carburant = 'E85' THEN p.prix_carburant END) AS prix_e85,\n    MAX(CASE WHEN c.nom_carburant = 'GPLC' THEN p.prix_carburant END) AS prix_gplc\nFROM station s\nJOIN prix p ON s.id_station = p.id_station\nJOIN carburant c ON p.id_carburant = c.id_carburant\nGROUP BY s.id_station, s.nom_ville, s.latitude, s.longitude;\n"
    }
   ]
  },
  {
   "title": "Analyse global du marché des carburants ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT c.nom_carburant, \nMIN(p.prix_carburant) AS prix_minimum, \nMAX(p.prix_carburant) AS prix_maximum, \nAVG(p.prix_carburant) AS prix_moyen \nFROM prix p JOIN carburant c ON p.id_carburant = c.id_carburant \nGROUP BY c.nom_carburant \nORDER BY prix_moyen DESC; "
    }
   ]
  },
  {
   "title": "Nombre moyen de service par ville et en générale ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    CONCAT(nom_ville, ' (', code_postal, ')') AS \"Commune\",\n    ROUND(AVG(nb_services), 1) AS \"Moyenne des services dans la Ville\",\n    (SELECT ROUND(AVG(nb_services), 1) FROM analyse_stations_carburants_v2) AS \"Moyenne Générale des services\"\nFROM public.analyse_stations_carburants_v2\nGROUP BY nom_ville,code_postal\nORDER BY \"Moyenne des services dans la Ville\" DESC\nLIMIT 10;"
    }
   ]
  }
 ]
}